# Generated by Django 3.2.9 on 2021-12-09 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=64)),
                ('type', models.IntegerField(choices=[(1, 'Liquid'), (2, 'Solid')])),
            ],
            options={
                'db_table': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='Teas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tea_name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'teas',
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.IntegerField(choices=[(1, 'Liquid'), (2, 'Solid')])),
                ('unit_type', models.IntegerField(choices=[(1, 'Metrical'), (2, 'Imperial')])),
                ('ratio_to_metrical', models.FloatField(default=0.035274)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='Brak opisu', max_length=1000)),
                ('units', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.units')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_settings',
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modification', models.DateTimeField(auto_now_add=True)),
                ('descripction', models.TextField(default='Brak', max_length=512)),
                ('recipe_name', models.CharField(max_length=128)),
                ('overall_upvotes', models.IntegerField(default=0)),
                ('last_month_upvotes', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=False)),
                ('brewing_temperature', models.FloatField(default=80)),
                ('brewing_time', models.FloatField(default=60)),
                ('mixing_time', models.FloatField(default=15)),
                ('is_favourite', models.BooleanField(default=False)),
                ('tea_herbs_ammount', models.FloatField(default=15)),
                ('tea_portion', models.FloatField(default=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('orginal_author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_author', to=settings.AUTH_USER_MODEL)),
                ('tea_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.teas')),
            ],
            options={
                'db_table': 'recipes',
                'ordering': ('-is_favourite', 'recipe_name'),
            },
        ),
        migrations.CreateModel(
            name='MachineContainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.FloatField(default=0, null=True)),
                ('container_number', models.IntegerField(choices=[(1, 'first_container_weight'), (2, 'second_container_weight'), (3, 'third_container_weight'), (4, 'fourth_container_weight')], default=0)),
                ('ingredient', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.ingredients')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_containers', to='authorization.machine')),
                ('tea', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.teas')),
            ],
            options={
                'db_table': 'machine_container',
            },
        ),
        migrations.CreateModel(
            name='IngredientsRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.ingredients')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='main_app.recipes')),
            ],
            options={
                'db_table': 'ingredients_recipes',
            },
        ),
        migrations.AddIndex(
            model_name='recipes',
            index=models.Index(fields=['author'], name='recipes_author__745c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='machinecontainers',
            index=models.Index(fields=['machine'], name='machine_con_machine_f0874a_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredientsrecipes',
            index=models.Index(fields=['recipe'], name='ingredients_recipe__5c2af9_idx'),
        ),
    ]
