# Generated by Django 3.2.9 on 2021-11-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinecontainers',
            name='container_number',
            field=models.IntegerField(choices=[(0, 'first_container_weight'), (1, 'second_container_weight'), (2, 'third_container_weight')], default=0),
        ),
    ]
