# Generated by Django 3.2.9 on 2021-12-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20211207_2202'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='machinecontainers',
            index=models.Index(fields=['machine'], name='machine_con_machine_f0874a_idx'),
        ),
    ]
