# Generated by Django 3.2.9 on 2021-11-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_machinecontainers_container_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinecontainers',
            name='container_number',
            field=models.IntegerField(choices=[(1, 'first_container_weight'), (2, 'second_container_weight'), (3, 'third_container_weight')], default=0),
        ),
    ]
