# Generated by Django 3.2.9 on 2021-11-09 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_machinecontainers_container_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinecontainers',
            name='ammount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='machinecontainers',
            name='ingredient',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.ingerdients'),
        ),
    ]
