# Generated by Django 3.2.9 on 2021-11-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20211110_0006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unit',
            new_name='Units',
        ),
        migrations.AlterField(
            model_name='recipes',
            name='tea_herbs_ammount',
            field=models.FloatField(default=15),
        ),
    ]
