# Generated by Django 3.2.9 on 2021-11-13 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20211112_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsrecipes',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='main_app.recipes'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='descripction',
            field=models.TextField(default='Brak', max_length=1023),
        ),
    ]
