# Generated by Django 3.2.9 on 2021-11-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20211113_0259'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingerdients',
            new_name='Ingredients',
        ),
    ]
