# Generated by Django 3.2.9 on 2021-11-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_ingerdients_ingredients'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ingredientsrecipes',
            index=models.Index(fields=['recipe'], name='ingredients_recipe__5c2af9_idx'),
        ),
        migrations.AddIndex(
            model_name='recipes',
            index=models.Index(fields=['author'], name='recipes_author__745c9c_idx'),
        ),
    ]
