# Generated by Django 4.0.1 on 2022-02-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='type',
            field=models.IntegerField(choices=[(1, 'Liquid'), (2, 'Solid')], default=0),
        ),
    ]
