# Generated by Django 3.2.9 on 2021-11-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20211107_1845'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Machines',
            new_name='Machine',
        ),
    ]
