# Generated by Django 3.2.9 on 2021-11-07 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_auto_20211107_2002'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='machine',
            table='server',
        ),
    ]
