# Generated by Django 3.2.9 on 2021-11-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_alter_machine_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='air_temperature',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='brewing_temperature',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='first_container_weight',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='is_mug_ready',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='is_user_active',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='mug_temperature',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='second_container_weight',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='state_of_the_tea_making_process',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='third_container_weight',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='water_container_weight',
            field=models.FloatField(default=0, null=True),
        ),
    ]
