# Generated by Django 3.2.9 on 2021-11-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_auto_20211107_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='is_user_active',
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_status',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='state_of_the_tea_making_process',
            field=models.IntegerField(choices=[(0, 'Ready To Work'), (1, 'Sending Request'), (2, 'Adding Tea Herbs'), (3, 'Boiling Water'), (4, 'Brewing'), (5, 'Mixing'), (6, 'Done')], default=0, null=True),
        ),
    ]
