# Generated by Django 3.2.9 on 2021-11-09 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_auto_20211108_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='first_container_weight',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='second_container_weight',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='third_container_weight',
        ),
    ]
