# Generated by Django 3.2.9 on 2021-12-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0009_auto_20211110_0006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['machine'], name='authorizati_machine_303d72_idx'),
        ),
    ]
