# Generated by Django 4.0.1 on 2022-02-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='machine',
            name='state_of_the_tea_making_process',
            field=models.IntegerField(choices=[(0, 'Ready To Work'), (1, 'Sending Request'), (2, 'Brewing'), (3, 'Adding Ingredients'), (4, 'Mixing'), (5, 'Done')], default=0, null=True),
        ),
    ]
